Convert to use ed25519 keys / multihash.
digitalbazaar/did-io pull request #30
Opened 2018-09-27 22:51 UTC by dmitrizagidulin

Based on Manu's work on did-veres-one.

(Depends on PR https://github.com/veres-one/veres-one-context/pull/3 ).

(WIP)

2018-09-28 20:26 UTC, dmitrizagidulin commented
Ready to review.

2018-09-28 21:05 UTC, mattcollier requested changes
I thought the aim was to have a did-veres-one dependency and use that code the generate the DID.  Is that correct?

2018-09-28 21:05 UTC, mattcollier commented on lib/methods/veres-one/veres-did-doc.js
> +      throw new Error('Cannot generate a cryptonym DID without a key')
missing semi.  There are a number of linting violations in the files in this repo.  Please lint with the latest rules.

2018-09-28 21:05 UTC, mattcollier commented on lib/methods/veres-one/veres-did-doc.js
> +        'ed25519' : 'forge',
one liner.

2018-09-28 21:53 UTC, dmitrizagidulin commented on lib/methods/veres-one/veres-did-doc.js
> +      throw new Error('Cannot generate a cryptonym DID without a key')
Thanks! Re-linted and fixed.

2018-09-28 21:54 UTC, dmitrizagidulin commented
> I thought the aim was to have a did-veres-one dependency and use that code the generate the DID. Is that correct?

The plan is to eventually extract Veres-related code out of did-io into did-veres-one, but it is not a priority. All downstream libs should be using `did-io` meanwhile, anyway.

2018-09-28 21:55 UTC, dmitrizagidulin commented on lib/methods/veres-one/veres-did-doc.js
> +        'ed25519' : 'forge',
Fixed, thanks.

2018-10-01 16:57 UTC, mattcollier commented
@dmitrizagidulin one of the tests is failing on node 8: https://travis-ci.org/digitalbazaar/did-io/jobs/435714189

2018-10-01 17:05 UTC, dmitrizagidulin commented
@mattcollier:

> one of the tests is failing on node 8: https://travis-ci.org/digitalbazaar/did-io/jobs/435714189

Yeah, that one's weird, it passes like 3/4 of the time, so something is off either with the algorithm or with the test. I need to check with @msporny or @dlongley

2018-10-04 18:45 UTC, dmitrizagidulin commented
Ok, I extracted fingerprint generating code to `LDKeyPair` class, and added a corresponding `verifyFingerprint()` function. The reason the test was failing had to do with the vagaries of base58-encoding. When we compare bytes directly, the fingerprints verify.

2018-10-04 18:59 UTC, mattcollier approved these changes

2018-10-04 18:59 UTC, mattcollier commented on lib/ld-key-pair.js
> +    return publicKeyBuffer.equals(fingerprintBuffer.slice(2));
has the information being discarded here already been validated?  Does it need to be?

2018-10-04 19:26 UTC, dmitrizagidulin commented on lib/ld-key-pair.js
> +    return publicKeyBuffer.equals(fingerprintBuffer.slice(2));
Erm, fair point. Now validating.

2018-10-04 20:48 UTC, dlongley approved these changes
LGTM

2018-10-04 20:49 UTC, merged